// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestBishop.CanMove_InvalidMove_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestBishop.CanMove_ValidMove_ReturnsTrue(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestKing.CanMove_TwoSquaresAway_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestKing.CanMove_OneSquareAway_ReturnsTrue(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestKnight.CanMove_ValidMove_ReturnsTrue(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestKnight.CanMove_InvalidMove_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestPawn.CanMove_ValidMove_ReturnsTrue(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestPawn.CanMove_InvalidMove_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestQueen.CanMove_InvalidMove_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestQueen.CanMove_ValidMove_ReturnsTrue(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestRook.TestConstructor(System.Boolean,System.Collections.Generic.IEnumerable{ChessLibrary.Rook})")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestRook.CanMove_ValidMove_ReturnsTrue(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestRook.CanMove_InvalidMove_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.ValidPseudo_ReturnTrue(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.InvalidPseudo_ReturnFalse(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.GoodPassword_ReturnTrue(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.InvalidPassword_ReturnFalse(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.GoodColor_ReturnTrue(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.WrongColor_ReturnTrue(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.GoodBoolConnected_ReturnTrue(System.String,System.String,ChessLibrary.Color,System.Boolean,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestUser.WrongBoolConnected(System.String,System.String,ChessLibrary.Color,System.Nullable{System.Boolean},System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<En attente>", Scope = "member", Target = "~M:ChessUnitTest.UnitTestGame.CanMove_InvalidMove_ThrowsException(System.Int32,System.Int32,System.Int32,System.Int32)")]
